[master 46e7c91] update
 26 files changed, 2035553 insertions(+), 34 deletions(-)
 rewrite nohup.out (100%)
 delete mode 100755 script/content_to_fasttest.sh
 create mode 100755 script/context_to_fasttest.sh
 create mode 100644 script/context_to_file.py
 create mode 100644 script/delete.pkl
 delete mode 100644 script/fasttest_lgbm.py
 create mode 100644 script/fasttext_feature.py
 create mode 100644 script/fasttext_feature_muti.py
 create mode 100644 script/fasttext_lgbm.py
 create mode 100644 script/file_to_vector_test.py
 create mode 100644 script/file_to_vector_test_desc.py
 create mode 100644 script/file_to_vector_train.py
 create mode 100644 script/file_to_vector_train_desc.py
 create mode 160000 script/proNet-core
 create mode 100644 solution/delete.py
 create mode 100644 solution/ensemble/ensemble.py
 create mode 100644 solution/ensemble/link.txt
 create mode 100644 solution/ensemble/subb_0.2211.csv
 create mode 100644 solution/lgbm_0.2223_fasttext_aggr_0.2229.py
 create mode 100644 solution/lgbm_0.2223_fasttext_aggr_20.py
 create mode 100644 solution/lgbm_0.2226_aggr.py
 create mode 100644 submit/ensemble_0.2211.csv
 create mode 100644 submit/lgbm_0.2223_fasttext_aggr_0.2229.py
 create mode 100644 submit/submission_0.2226_aggr.csv
 create mode 100755 submit/submit.sh
To git@github.com:CoolSheng/Kaggle--Avito-Demand-Prediction-Challenge.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'git@github.com:CoolSheng/Kaggle--Avito-Demand-Prediction-Challenge.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
